import "./style.css";
import "./dashboard-polish.css";
import { initAuth } from "./auth";
import { initConnectionBanner } from "./connection";
import { initTabBar } from "./components/tabBar";
import { initTopBar } from "./components/topBar";
import { initIdentitySwitcher } from "./identitySwitcher";
import { initPresence } from "./presence";
import { initTabRouter } from "./router";
import { initSidebarToggle } from "./sidebarToggle";
import { initTheme } from "./theme";
import { initUpdater } from "./updater";
import { initActivityFeed } from "./views/activityFeed";
import { initChargeFeed } from "./views/chargeFeed";
import { initAiProspecting } from "./views/aiProspecting";
import { initActivityModalOverlay } from "./components/activityModal";
import { initCommandPalette } from "./components/commandPalette";
import { initActionCentre } from "./views/actionCentre";
import { initAnalytics } from "./views/analytics";
import { initCalendar } from "./views/calendar";
import { initCallQueue } from "./views/callQueue";
import { initColdCallLists } from "./views/coldCallLists";
import { initDashboard } from "./views/dashboard";
import { initEmailWriter } from "./views/emailWriter";
import { initOpportunityWorkspace } from "./views/opportunityWorkspace";
import { initSalesIntelligence } from "./views/salesIntelligence";
import { initSequences } from "./views/sequences";
import { initListCampaign } from "./views/listCampaign";
import { initOutreach } from "./views/outreach";
import { initSettings } from "./views/settings";
import { initWinBackCampaign } from "./views/winBackCampaign";

initTheme();
initIdentitySwitcher();
initActivityModalOverlay();
initDashboard();
initActivityFeed();
initChargeFeed();
initActionCentre();
initAiProspecting();
initCallQueue();
initOpportunityWorkspace();
initColdCallLists();
initSalesIntelligence();
initEmailWriter();
initSequences();
initListCampaign();
initOutreach();
initWinBackCampaign();
initCalendar();
initAnalytics();
initSettings();
initTabBar();
initTopBar();
initTabRouter();
initSidebarToggle();
initPresence();
initCommandPalette();

void initAuth();
void initUpdater();
initConnectionBanner();

// Real version in the sidebar (replaces the hardcoded placeholder)
void import("@tauri-apps/api/app").then(async ({ getVersion }) => {
  const el = document.querySelector(".sidebar-version-label");
  if (el) el.textContent = `v${await getVersion()}`;
});
